name:                hackage-doc-mcp
version:             0.0.1.0
github:              "tusharad/hackage-doc-mcp"
license:             MIT
author:              "Tushar Adhatrao"
maintainer:          "tusharadhatrao@gmail.com"
copyright:           "2026 Tushar Adhatrao"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            MCP server for hackage documenation
category:            Web, AI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hackage-doc-mcp#readme>

dependencies:
- aeson >= 2.2
- base >= 4.7 && < 5
- bytestring >= 0.12
- http-conduit >= 2.3
- http-types >= 0.12
- mcp-server >= 0.1
- scalpel >= 0.6
- tagsoup >= 0.14
- text >= 2.1 

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
 - DeriveGeneric 
 - OverloadedStrings
 - RecordWildCards 

library:
  source-dirs: src

executables:
  hackage-doc-mcp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackage-doc-mcp

tests:
  hackage-doc-mcp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hackage-doc-mcp
    - tasty >= 1.4
    - tasty-hunit >= 0.10
    - HUnit >= 1.6
