name: development pipeline

on:
  push:
    branches: ["develop"]

jobs:
  build-binaries-and-image:
    name: Build & Push (${{ matrix.arch-tag }})
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch-tag: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm 
            arch-tag: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build binary for ${{ matrix.platform }}
        uses: freckle/stack-action@v5
        with:
          cache-prefix: shared-
          stack-build-arguments: --copy-bins --local-bin-path ./release --ghc-options='-O2'

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v4

      - name: extract version number
        run: |
          version=$(grep -E '^version:' *.cabal | awk '{print $2}')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: build docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}
          tags: tusharknight8/hackage-doc-mcp:${{ env.VERSION }}-${{ matrix.arch-tag }}
          cache-from: type=gha,scope=hackage-doc-mcp
          cache-to: type=gha,mode=max,scope=hackage-doc-mcp
